### ISSUE TITLE
FR: Add custom/owned sounds

### ISSUE THREAD

**Issue by Vendergast** [MrVauxs/pf2e-graphics#108]
**Is your feature request related to a problem? Please describe.**
At the moment you can only choose SoundFiles from the sequencer database which a part of the jba, grpahics or any other module you have. If possible it would be nice to have a way to add custom sounds you own to chose from.

**Describe the solution you'd like**
Any solution which is possible to add own sounds.

If there is already a solution, my apologies in advance!

**Comment by MrVauxs** [comment]
You can choose any files you want. Just copy paste the filepath or URL.
