### ISSUE TITLE
[BUG] Errors when token has no owner

### ISSUE THREAD

**Issue by ChasarooniZ** [MrVauxs/pf2e-graphics#126]
- if token has no owner
- When it reaches `userKeys = user.getFlag('pf2e-graphics', 'customAnimations')`, there is no user to get the flag for and it errors out

Not sure how they ended up with a token with no owner (maybe a multi gm server thing) 
![image](https://github.com/user-attachments/assets/726df66c-1c1a-4da9-85a5-122f88c946b8)
![image](https://github.com/user-attachments/assets/4964d52c-8d3c-45ce-98e6-4bdb2773260a)

**Comment by MrVauxs** [comment]
How does a token have no owner, I need something to be able to replicate.

**Comment by fotoply** [comment]
I just managed to replicate this issue by using the official Kingmaker module.

Specifically I get it when I apply an effect to any of the actors that were previously imported with the adventure, regardless of it they are newly placed on the scene or not.

So the fix in https://github.com/MrVauxs/pf2e-graphics/commit/db6bcfa7079e1508e940cb0156bfe0383a5a23dc does not seem to work.

The ownership object looks identical to a newly created actor that does not inhibit this behavior.

Ownership of bugged actor:
![image](https://github.com/user-attachments/assets/548528e8-e0b4-41b3-b418-f9755f6e2cc3)
Ownership of functional actor.
![image](https://github.com/user-attachments/assets/c5b01eee-2d9d-4885-be43-62de6069dbbb)

**Comment by MrVauxs** [comment]
Please check if those IDs exist in your world.

If they don't that means ownership is not scrubbed on adventure import and now I have to validate whether said users ***even exist***.

**Comment by fotoply** [comment]
Yep, edited my comment, it does not exist in the world
