### ISSUE TITLE
JSON Schema

### ISSUE THREAD

**Issue by MrVauxs** [MrVauxs/pf2e-graphics#15]
**Is your feature request related to a problem? Please describe.**
Writing the data by hand can get annoying without a schema.

**Describe the solution you'd like**
JSON Schema. Generated by whatever.

**Describe alternatives you've considered**
Zod? AJV? Typescript-to-json-schema?

**Comment by ThiefMaster** [comment]
Using YAML or TOML instead of JSON might be a good alternative since both are way more human-friendly (and also allow putting comments which I guess might be useful for more complex definitions)

**Comment by MrVauxs** [comment]
> Using YAML or TOML instead of JSON might be a good alternative since both are way more human-friendly (and also allow putting comments which I guess might be useful for more complex definitions)

JSON schema is preferable for integration with code editors. I don't also believe in YAMLs readability, but that's my personal preference.
