### ISSUE TITLE
Option to remove the text label for the graphics button in the sheet header

### ISSUE THREAD

**Issue by Peach774** [MrVauxs/pf2e-graphics#154]
**Is your feature request related to a problem? Please describe.**
I would like the option to hide the text label part of this label - 
![image](https://github.com/user-attachments/assets/06cb5713-5948-45eb-afbf-92d8639d42ba)

**Describe the solution you'd like**
It would just be the film icon, not the text that says 'Graphics'

**Comment by sshryock0615** [comment]
I wanted to add to this,  the option to move the Graphics button from header to sheet doesn't seem to be working,

**Comment by MrVauxs** [comment]
> I wanted to add to this, the option to move the Graphics button from header to sheet doesn't seem to be working,

It works.
![chrome_dU0cBnlnQ5](https://github.com/user-attachments/assets/32f3023c-e623-4f69-9a99-edfe1d33697b)

It doesnt do anything on other sheets.

**Comment by sshryock0615** [comment]
I should have specified, I am in fact hitting this issue for NPCs. Is that on a roadmap or is it simply not feasible?

**Comment by MrVauxs** [comment]
All sheets that have tabs will have it now.
![chrome_2cAlu5vw0s](https://github.com/user-attachments/assets/89a941d3-baef-472e-ba0d-84fe80ac8f64)

**Comment by sshryock0615** [comment]
![image](https://github.com/user-attachments/assets/c5fca959-9bc7-4483-9636-0f7018050f0d)
Is this just an older style sheet that doesn't work with those changes? It has tabs but they do appear to be a little different.

**Comment by MrVauxs** [comment]
> Is this just an older style sheet that doesn't work with those changes? It has tabs but they do appear to be a little different.

I said **will**. This change is not released yet. Please be patient.

**Comment by sshryock0615** [comment]
Ah I follow you. No rush or anything I appreciate everything you do :)
