### ISSUE TITLE
[BUG] New update has caused to disappear from module list

### ISSUE THREAD

**Issue by WizardForHire123** [MrVauxs/pf2e-graphics#174]
its vanished

update and check the module list

![image](https://github.com/user-attachments/assets/09aa116d-cbd0-486c-afa5-3c93c790564c)

**Comment by WizardForHire123** [comment]
we are on forge 3 of us could replicate

**Comment by MrVauxs** [comment]
I swear, forge...

**Comment by MrVauxs** [comment]
Fixed in 0.9.1.

**Comment by WizardForHire123** [comment]
we appreciates you
