### ISSUE TITLE
[BUG] Title

### ISSUE THREAD

**Issue by Et3rnus** [MrVauxs/pf2e-graphics#232]
**Describe the bug**
After this last update, updating failed for me, with the following error: 
Metadata validation failed for module "pf2e-graphics": The file "dist/pf2e-graphics.js" included by module pf2e-graphics does not exist

**To Reproduce**
Impossible, Pf2e graphics seemingly uninstalled itself and I can not re-install it.

**Expected behavior**
Being able to reinstall the module.

> [!important] Versions
>
> - Foundry: Latest. 
> - Sequencer: Latest update, updated all my modules 1 day ago and today again. Pf2e Graphics broke on today's update.
> - PF2e Graphics: Latest update, posted today.

**Comment by MrVauxs** [comment]
Install v0.9.3
