### ISSUE TITLE
Put style variables into `:root`

### ISSUE THREAD

**Issue by farling42** [MrVauxs/pf2e-graphics#322]
When looking at the styles in a journal entry I noticed that you have some CSS variables set with a selector of "*, :before, :after"

This means that they are appearing for every single element as well as every single parent element, repeatedly.

It would be much tidier (and possibly involve less CSS processing by the browser) to simply place them in ":root" like is done for the core Foundry and PF2e CSS variables.

Alternatively, apply some additional scope so that they aren't referenced by most of the UI elements at all.

**Comment by MrVauxs** [comment]
It's done by Tailwind, and I believe it has negligible if any performance impact. But I'll see about limiting it.

**Comment by MrVauxs** [comment]
todo: add https://www.npmjs.com/package/tailwindcss-scoped-preflight?activeTab=readme

**Comment by MrVauxs** [comment]
Resolved for v1.
