### ISSUE TITLE
[BUG] Error in JSON for Water Kineticist Elemental Blast Animation

### ISSUE THREAD

**Issue by Dwarfinator1** [MrVauxs/pf2e-graphics#35]
**Describe the bug**
There is an error in the JSON code for the Elemental Blast animation specifically for the Water Kineticist which is shown below.
The kinetic gate is marked as ice which is a nonexistent gate, it should be water, this leads to the animation not playing for the Water Kineticists Elemental Blast as it is not recognized by the preset.

```
{
  "item:slug:elemental-blast": [
    {
      "reference": "item:slug:electric-arc",
      "trigger": "attack-roll",
      "predicate": [
        "kinetic-gate:air",
        "item:trait:electricity"
      ]
    },
    {
      "trigger": "attack-roll",
      "preset": "ranged",
      "file": "jb2a.spell_projectile.ice_shard.blue",
      "predicate": [
        "kinetic-gate:ice",
        "item:trait:cold"
      ]
    },
    {
      "trigger": "attack-roll",
      "preset": "ranged",
      "file": "jb2a.fire_bolt.orange",
      "predicate": [
        "kinetic-gate:fire",
        "item:trait:fire"
      ]
    }
  ]
}
```

**To Reproduce**
Tested the Elemental Blast of the Water Kineticist multiple times on multiple targets (Am the GM).

Did the same test with the Fire Kineticist and it worked immediately.

**Expected Behaviour**
It should play the animation on the attack roll, but it does not.

**Screenshots**
Video of issue:

[https://cdn.discordapp.com/attachments/836436536119132171/1273377195087106198/2024-08-14_15-23-08.mp4?ex=66be646d&is=66bd12ed&hm=8efc753ac3f312eedd08ed153a443e41c57a1bf1d7ee092fa8d0bb8dbc0538ea&](url)

> [!important] Versions
>
> - Foundry: v12.330
> - Sequencer: 3.2.14
> - PF2e Graphics: 0.6.4

**Comment by MrVauxs** [comment]
Fixed in newest version by not associating the animations with gates but the traits they take.
