### ISSUE TITLE
Combining Multiple Animations

### ISSUE THREAD

**Issue by 7H3LaughingMan** [MrVauxs/pf2e-graphics#43]
**Is your feature request related to a problem? Please describe.**
Combine animations from different sources into a single sequence.

**Describe the solution you'd like**
The idea is to be able to setup generic animations that can be reused or overridden in certain circumstances that are used before/after the main animation of something. For example, being able to setup a generic casting animation that can play before a spell's animation. Or having another animation play after a spell's animation to represent the result of a saving throwing.

For example we have the below animation that is just a generic casting animation to be played when a saving throw is made on the caster. Having a way to play this first before the main animation from whatever spell is cast.

```
{
	"item:type:spell": [
		"trigger": "saving-throw",
		"preset": "onToken",
		"file": "jb2a.cast_generic.01.yellow.0",
		"options": {
			"preset": "origin"
		}
	]
}
```

Here is an example of an animation to play on the target of a saving-throw when they critically succeed.

```
{
	"item:type:spell": [
		"trigger": "saving-throw",
		"preset": "onToken",
		"file": "jb2a.shield.01.outro_explode.blue",
		"predicate": [
			"outcome:criticalSuccess"
		],
		"options": {
			"preset": "target"
		}
	]
}
```

There also needs to be a way to have a spell override the animations if they want to do something fancier, or for user/actor animations to override them.

Another example I can provide but don't know how to program is regarding attack rolls with strikes. For example if a player is attacking a monster with a sword being able to have their token take a small step to their target before attacking and then after they are done stepping back.

**Comment by MrVauxs** [comment]
Note: Also required for roll result animations such as a Critical Hit SFX or Critical Miss Text.
