### ISSUE TITLE
[BUG] Custom Animation Menu Doesn't Work

### ISSUE THREAD

**Issue by ZzinnerGamer** [MrVauxs/pf2e-graphics#88]
**Describe the bug**
Adding effects to items on the repository causes an error.

**To Reproduce**
Step by step:

1 Create an item (or use any item)

2 Enter the Animation Menu and Custom Animation

3 Click on +

4 error pops on console

The item stills there, works fine, but whenever i try to open the animation menu gives error on the console and doesnt open the animation menu. Creating the item in actors has the same behaviour.

5 Delete the item

6 Error pops

7 Try to open the animation menu on any item, wichever it is, world items, compendium items, actor items... error pops on the console and the animation menu cannot be closed.

If i insist to open the menu (on the attached video) it end up oppening, but cannot do anything.
[Graphics Error.webm](https://github.com/user-attachments/assets/cbe29b2b-ba5b-4405-8c94-d46c1665d4a5)
![imagen_2024-08-22_175549137](https://github.com/user-attachments/assets/b87c42aa-df40-4d3d-a09d-af9e05e17a5c)

**Expected behavior**
Should open and let me edit the item animation doesnt it?

> - Foundry: v12.331
> - Sequencer: 3.2.16
> - PF2e Graphics: 0.7.4

**Comment by MrVauxs** [comment]
Do you have JB2A enabled?
